### ISSUE TITLE
Replacement contact for carol beardmore who retired.

### ISSUE THREAD

**Issue by thoufer** [thoufer/mbp-metadatacatalog#22]
Who is the contact in place of Carol Beardmore (retired) for the cooperative MX surveys ... ask Ken Kreise or Dave Olson about status of asset 

ID of 10 in google sheet.

**Comment by Rrau** [comment]
emailed Jennie Duberstein (Sonoran JV coordinator) to ask about Carol's replacement and who might be the new contact for this survey and data.

**Comment by Rrau** [comment]
Jennie Duberstein is still in the process of hiring Carol's replacement, so I will put her as the main contact.  I'm still keeping Carol as the data contact since she is still organizing and going through her files.  I included her personal email and cell phone for contacts.  Once Jennie hire's the new person and Carol transfers everything over to the new person, then we can update this field.
